config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
      resources :users
      resources :properties
      resources :property_images
      resources :bookings

      root to: "users#index"
    end
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_up: 'register', sign_out: 'logout'}

  resources :properties, :only => [:show, :index] do
      resources :bookings, :except => [:show, :index]
  end

  post '/contact', to: 'home#contact', as: 'contact'

  root to: "home#index"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/property.rb
require 'elasticsearch/model'

class Property < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged
    
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks
    settings index: { number_of_shards: 1 }

    belongs_to :user

    has_many :property_images, dependent: :destroy
    has_many :bookings, dependent: :destroy

    accepts_nested_attributes_for :property_images, allow_destroy: true

    def images
      # code
    end
end

app/controllers/admin/properties_controller.rb
module Admin
  class PropertiesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
   def find_resource(param)
     Property.friendly.find(param)
   end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
    def create
      @property = current_user.properties.create resource_params
      if params[:images]
          params[:images].each do |image|
              @property.property_images.create(image: image)
          end
      end
      if @property
          respond_to do |format|
            format.html { redirect_to admin_property_path @property, notice: 'Property created successfuly' }
            format.json { render json: @property }
          end
      else
          respond_to do |format|
            format.html {redirect_to :back, notice: 'Property creation failed' }
            format.json { render json: @property.errors }
          end
      end
    end
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  def index
      @title = 'Properties'
      if params[:q]
          @properties = Elasticsearch::Model.search(params[:q]).records
          if params[:price]
              @properties = @properties.to_a.select do |prop|
                  prop.price.to_f <= params[:price].to_f
              end
          end
      else
          @properties = Property.all
      end
  end

  def show
      @booking = @property.bookings.new
      @title = @property.title
  end

  private
    def set_property
      @property = Property.friendly.find(params[:id])
    end
end

app/helpers/admin/properties_helper.rb
module Admin::PropertiesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/admin/properties/_form.html.erb
    <%= form_with(model: property, local: true, multipart: true, url: admin_properties_path, id: 'form') do |form| %>
      <% if property.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

          <ul>
            <% property.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="col-md-12 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
          <div class="card-body">
            <div class="align-items-center">
                <div class="row">
                    <div class="col-md-6  border-right-success">
                        <div class="card-title">
                            <h4 class="h4">Property Information</h4>
                        </div>
                        <div class="form-group">
                          <%= form.label :title %>
                          <%= form.text_field :title, class: 'form-control' %>
                        </div>

                        <div class="form-group">
                          <%= form.label :address %>
                          <%= form.text_field :address, class: 'form-control' %>
                        </div>

                        <div class="row">
                            <div class="col-md-6 form-group">
                              <%= form.label :city %>
                              <%= form.text_field :city, class: 'form-control' %>
                            </div>
                            <div class="col-md-6 form-group">
                              <%= form.label :country %>
                              <%= form.text_field :country, class: 'form-control' %>
                            </div>
                        </div>

                        <div class="form-group">
                          <%= form.label :price %>
                          <%= form.text_field :price, class: 'form-control' %>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-6">
                                <%= form.label "Hosing Units" %>
                                <%= form.number_field :units, class: 'form-control' %>
                            </div>

                            <div class="form-group col-sm-6">
                                <%= form.label :bedrooms %>
                                <%= form.number_field :bedrooms, class: 'form-control' %>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-6">
                                <%= form.label :dinig_rooms %>
                                <%= form.number_field :dinig_rooms, class: 'form-control' %>
                            </div>

                            <div class="form-group col-sm-6">
                                <%= form.label :kitchens %>
                                <%= form.number_field :kitchens, class: 'form-control' %>
                            </div>
                        </div>

                        <div class="row">
                            <div class="form-group col-sm-6">
                                <%= form.label "Yard (sqm)" %>
                                <%= form.text_field :yard, class: 'form-control' %>
                            </div>

                            <div class="form-group col-sm-6">
                                <%= form.label :rooms %>
                                <%= form.number_field :rooms, class: 'form-control' %>
                            </div>
                        </div>

                        <div class="form-group">
                          <%= form.label :description %>
                          <%= form.text_area :description, class: 'form-control' %>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="card-title">
                            <h4 class="h4">Images</h4>
                        </div>
                        <div class="form-group col-md-12">
                            <input type="file" name="images[]" class="filepond" value="">
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <%= form.submit 'Create Property', class: 'btn btn-primary btn-block' %>
                    </div>
                </div>
            </div>
          </div>
        </div>
      </div>
<% end %>

app/views/admin/properties/_loader.html.erb
<div class="bg-primary d-none" id="parent-loader">
    <div id="circle">
      <div class="loader">
        <div class="loader">
            <div class="loader">
               <div class="loader">

               </div>
            </div>
        </div>
      </div>
      <div class="text-center">
          <span class="text-white">Processing...</span>
      </div>
    </div>
</div>

app/views/admin/properties/new.html.erb
<%#
# New

This view is the template for the "new resource" page.
It displays a header, and then renders the `_form` partial
to do the heavy lifting.

## Local variables:

- `page`:
  An instance of [Administrate::Page::Form][1].
  Contains helper methods to help display a form,
  and knows which attributes should be displayed in the resource's form.

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Form
%>

<% content_for(:title) do %>
  <%= t(
    "administrate.actions.new_resource",
    name: display_resource_name(page.resource_name).titleize
  ) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title">
    <%= content_for(:title) %>
  </h1>

  <div>
    <%= link_to t("administrate.actions.back"), :back, class: "button" %>
  </div>
</header>

<section class="main-content__body">
  <%= render "form", page: page %>
  <%= render 'loader' %>
</section>